kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: spring-training-binary
  namespace: spring-training-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'spring-training:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  completionDeadlineSeconds: 1800
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'openjdk-11-rhel7:1.1'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers: []
  runPolicy: Serial
